import turtle
w = turtle.Screen()
alex = turtle.Turtle()
alex.color("blue")
bogdan = turtle.Turtle()
bogdan.color(1,0.5,0.5)
bogdan.left(90)
bogdan.forward(75)
bogdan.color("green")
bogdan.rt(45)
bogdan.fd(90)

alex.fd(150)
alex.lt(90)
alex.fd(75)
alex.fd(150)
alex.lt(90)
alex.fd(75)
turtle.done()

